-- Normalize validation_verdict.reason_codes and .explanations from concatenated
-- string blobs into a proper child table. Tracked as lib-persistence REVIEW.md
-- Finding #4.
--
-- Why this migration:
--   * The old varchar(4000) reason_codes column required `WHERE reason_codes
--     LIKE '%X%'` queries to find candidates rejected for a specific reason —
--     a full-table scan with false-positive risk if a future reason code is a
--     prefix of another.
--   * The 4000-char limit silently truncated long explanation chains.
--   * L8 calibration analyses (per lib-analytics/META_ADAPTATION_FEEDBACK.md
--     §3.1 "Dimension attribution") need per-reason-code drift queries.
--
-- After this migration:
--   * Each verdict's reasons live as one row per code in validation_verdict_reason.
--   * The original blob columns remain on the table so historical rows are
--     readable while the application transitions; new writes populate the
--     child table only. A future V13 may drop the blob columns.
--
-- SAFETY: existing rows are backfilled below. If your validation_verdict
-- table is small (single-user discretionary trading platform), the backfill
-- runs inline. On a large table consider running the backfill in batches.

create table validation_verdict_reason (
    id bigint generated by default as identity primary key,
    verdict_id bigint not null,
    reason_code varchar(64) not null,
    explanation varchar(2000),
    sort_order smallint not null,
    constraint fk_validation_verdict_reason_verdict
        foreign key (verdict_id)
        references validation_verdict(id)
        on delete cascade
);

-- The (verdict_id, sort_order) pair uniquely identifies a reason within a verdict;
-- this also serves as the natural index for joined queries.
create unique index uq_validation_verdict_reason_verdict_sort
    on validation_verdict_reason(verdict_id, sort_order);

-- Index for the L8 calibration query "find verdicts that fired reason X".
create index idx_validation_verdict_reason_code
    on validation_verdict_reason(reason_code);

-- Backfill from existing concatenated columns. We use a recursive CTE to
-- split the comma-separated reason_codes into rows, then left-join the
-- pipe-separated explanations on position.
--
-- H2 supports recursive CTE syntax; Postgres does too. Other engines may
-- need a different splitting strategy.
insert into validation_verdict_reason (verdict_id, reason_code, explanation, sort_order)
with recursive codes (verdict_id, code, rest, idx) as (
    -- seed: first code (or full string if no comma) for every verdict
    select id,
           case when position(',' in coalesce(reason_codes, '')) > 0
                then trim(substring(reason_codes from 1 for position(',' in reason_codes) - 1))
                else trim(coalesce(reason_codes, ''))
           end as code,
           case when position(',' in coalesce(reason_codes, '')) > 0
                then substring(reason_codes from position(',' in reason_codes) + 1)
                else null
           end as rest,
           0 as idx
      from validation_verdict
     where reason_codes is not null and length(trim(reason_codes)) > 0
    union all
    -- recursion: peel off the next code from the remaining tail
    select verdict_id,
           case when position(',' in rest) > 0
                then trim(substring(rest from 1 for position(',' in rest) - 1))
                else trim(rest)
           end as code,
           case when position(',' in rest) > 0
                then substring(rest from position(',' in rest) + 1)
                else null
           end as rest,
           idx + 1 as idx
      from codes
     where rest is not null and length(trim(rest)) > 0
),
explanations (verdict_id, explanation, rest, idx) as (
    select id,
           case when position('|' in coalesce(explanations, '')) > 0
                then trim(substring(explanations from 1 for position('|' in explanations) - 1))
                else trim(coalesce(explanations, ''))
           end as explanation,
           case when position('|' in coalesce(explanations, '')) > 0
                then substring(explanations from position('|' in explanations) + 1)
                else null
           end as rest,
           0 as idx
      from validation_verdict
     where explanations is not null and length(trim(explanations)) > 0
    union all
    select verdict_id,
           case when position('|' in rest) > 0
                then trim(substring(rest from 1 for position('|' in rest) - 1))
                else trim(rest)
           end as explanation,
           case when position('|' in rest) > 0
                then substring(rest from position('|' in rest) + 1)
                else null
           end as rest,
           idx + 1 as idx
      from explanations
     where rest is not null and length(trim(rest)) > 0
)
select c.verdict_id, c.code, e.explanation, cast(c.idx as smallint)
  from codes c
  left join explanations e
    on e.verdict_id = c.verdict_id and e.idx = c.idx
 where c.code is not null and length(c.code) > 0;
