-- V18: durable market-state snapshots produced by the optional intraday scheduler.

create table market_state_snapshot (
    id bigint generated by default as identity primary key,
    symbol varchar(16) not null,
    observed_at timestamp not null,
    source varchar(64) not null,
    regime_label varchar(64) not null,
    confidence double precision not null,
    equilibrium_restoration_probability double precision not null,
    deployment_supported boolean not null,
    session_vwap double precision not null,
    latest_close double precision not null,
    vwap_distance_percent double precision not null,
    vwap_reclaim_strength double precision not null,
    directional_persistence_score double precision not null,
    rotational_quality_score double precision not null,
    intraday_trend_strength double precision not null,
    above_vwap boolean not null,
    bar_count integer not null,
    notes text,
    created_at timestamp not null default current_timestamp
);

create index idx_market_state_snapshot_symbol_observed_at
    on market_state_snapshot(symbol, observed_at desc);

create index idx_market_state_snapshot_observed_at
    on market_state_snapshot(observed_at desc);
