-- V19: broker call audit rows for Schwab OAuth and future broker lifecycle calls.

create table broker_call_log (
    id bigint generated by default as identity primary key,
    recorded_at timestamp not null,
    endpoint varchar(256) not null,
    request_body text,
    response_status integer not null,
    response_body text,
    correlation_id varchar(128) not null,
    client_order_id varchar(128),
    created_at timestamp not null default current_timestamp
);

create index idx_broker_call_log_recorded_at
    on broker_call_log(recorded_at desc);

create index idx_broker_call_log_correlation_id
    on broker_call_log(correlation_id);
