CREATE TABLE candidate (
    candidate_id VARCHAR(64) PRIMARY KEY,
    symbol VARCHAR(16) NOT NULL,
    company_name VARCHAR(256),
    catalyst_type VARCHAR(64) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_id VARCHAR(256),
    source_url VARCHAR(1024),
    observed_at TIMESTAMP NOT NULL,
    headline VARCHAR(512),
    summary VARCHAR(4000)
);

CREATE INDEX idx_candidate_symbol_observed_at
    ON candidate(symbol, observed_at DESC);

CREATE TABLE validation_verdict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    symbol VARCHAR(16) NOT NULL,
    verdict VARCHAR(32) NOT NULL,
    deployment_tier VARCHAR(32) NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    reason_codes VARCHAR(4000),
    explanations VARCHAR(8000),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_validation_verdict_candidate_created_at
    ON validation_verdict(candidate_id, created_at DESC);

CREATE INDEX idx_validation_verdict_symbol_created_at
    ON validation_verdict(symbol, created_at DESC);
