create table candidate (
    candidate_id varchar(64) primary key,
    symbol varchar(16) not null,
    company_name varchar(256),
    catalyst_type varchar(64) not null,
    source_type varchar(64) not null,
    source_id varchar(256),
    source_url varchar(1024),
    observed_at timestamp not null,
    headline varchar(512),
    summary varchar(4000)
);

create index idx_candidate_symbol_observed_at
    on candidate(symbol, observed_at desc);

create table market_bar (
    id bigint generated by default as identity primary key,
    symbol varchar(16) not null,
    bar_date date not null,
    open_price double precision not null,
    high_price double precision not null,
    low_price double precision not null,
    close_price double precision not null,
    volume bigint not null,
    unique(symbol, bar_date)
);

create index idx_market_bar_symbol_date
    on market_bar(symbol, bar_date desc);

create table market_snapshot (
    id bigint generated by default as identity primary key,
    candidate_id varchar(64) not null,
    symbol varchar(16) not null,
    observed_at timestamp not null,
    latest_close double precision not null,
    previous_close double precision not null,
    gap_percent double precision not null,
    average_true_range double precision not null,
    range_position double precision not null,
    average_volume double precision not null,
    liquidity_score double precision not null,
    volatility_stability_score double precision not null,
    quality varchar(64) not null,
    notes varchar(4000)
);

create table validation_verdict (
    id bigint generated by default as identity primary key,
    candidate_id varchar(64) not null,
    symbol varchar(16) not null,
    verdict varchar(32) not null,
    deployment_tier varchar(32) not null,
    score double precision not null,
    reason_codes varchar(4000),
    explanations varchar(8000),
    created_at timestamp not null
);

create index idx_validation_symbol_created_at
    on validation_verdict(symbol, created_at desc);

create table backtest_result (
    id bigint generated by default as identity primary key,
    run_id varchar(64) not null,
    strategy_name varchar(128) not null,
    symbol varchar(16) not null,
    candidate_id varchar(64) not null,
    verdict varchar(32) not null,
    score double precision not null,
    tested_at timestamp not null
);

create index idx_backtest_run_id
    on backtest_result(run_id);
