-- Long-horizon calibration: realized outcomes for closed trades, used by
-- LongHorizonCalibrationAnalyzer (MD Layer 8 — Meta-System Adaptation).
-- Each row is one outcome sample: the candidate's scoring breakdown at decision
-- time, plus what actually happened after.

create table calibration_outcome (
    id bigint generated by default as identity primary key,
    candidate_id varchar(128) not null,
    symbol varchar(16) not null,
    observed_at timestamp not null,

    -- Snapshot of the candidate's scoring breakdown at decision time
    structural_reality_score    double precision not null,
    material_significance_score double precision not null,
    earlyness_score             double precision not null,
    equilibrium_quality_score   double precision not null,
    reflexivity_potential_score double precision not null,
    asymmetry_score             double precision not null,
    regime_compatibility_score  double precision not null,
    deployment_confidence_score double precision not null,

    -- Realized outcome
    realized_return double precision not null,
    max_drawdown    double precision not null,
    days_held       integer          not null,
    thesis_worked   boolean          not null
);

create index idx_calibration_outcome_symbol_observed_at
    on calibration_outcome(symbol, observed_at desc);

create index idx_calibration_outcome_observed_at
    on calibration_outcome(observed_at desc);
