-- Persistent storage for the current Schwab OAuth access + refresh token.
-- One row per environment — there is no concept of multiple users in this
-- single-trader platform.

create table schwab_token (
    id            bigint generated by default as identity primary key,
    access_token  varchar(4000) not null,
    refresh_token varchar(4000) not null,
    issued_at     timestamp     not null,
    expires_at    timestamp     not null,
    token_type    varchar(32)   not null default 'Bearer'
);

create index idx_schwab_token_issued_at
    on schwab_token(issued_at desc);
