create table analytics_snapshot (
    id bigint generated by default as identity primary key,
    candidate_id varchar(64) not null,
    symbol varchar(16) not null,
    observed_at timestamp not null,
    regime_label varchar(64) not null,
    regime_compatibility_score double precision not null,
    asymmetry_score double precision not null,
    equilibrium_quality_score double precision not null,
    reflexivity_potential_score double precision not null,
    deployment_confidence_score double precision not null,
    reason_notes varchar(4000),
    constraint fk_analytics_snapshot_candidate
        foreign key (candidate_id) references candidate(candidate_id)
);

create index idx_analytics_snapshot_candidate_id
    on analytics_snapshot(candidate_id);

create index idx_analytics_snapshot_symbol_observed
    on analytics_snapshot(symbol, observed_at desc);
