create table trader_note (
    id bigint generated by default as identity primary key,
    candidate_id varchar(64) not null,
    symbol varchar(16) not null,
    note_text varchar(4000) not null,
    created_at timestamp not null,
    author varchar(128),
    constraint fk_trader_note_candidate
        foreign key (candidate_id) references candidate(candidate_id)
);

create index idx_trader_note_candidate_id
    on trader_note(candidate_id);

create index idx_trader_note_created_at
    on trader_note(created_at desc);
