create table intraday_bar (
    id bigint generated by default as identity primary key,
    symbol varchar(16) not null,
    start_time timestamp not null,
    open_price double precision not null,
    high_price double precision not null,
    low_price double precision not null,
    close_price double precision not null,
    volume bigint not null,
    vwap double precision not null,
    created_at timestamp not null,
    unique(symbol, start_time)
);

create index idx_intraday_bar_symbol_start_time
    on intraday_bar(symbol, start_time desc);

create table market_quote_observation (
    id bigint generated by default as identity primary key,
    symbol varchar(16) not null,
    observed_at timestamp not null,
    last_price double precision not null,
    bid_price double precision not null,
    ask_price double precision not null,
    volume bigint not null,
    quality varchar(64) not null,
    notes varchar(4000)
);

create index idx_market_quote_symbol_observed_at
    on market_quote_observation(symbol, observed_at desc);

create table trade_history_import_batch (
    id bigint generated by default as identity primary key,
    imported_at timestamp not null,
    total_rows integer not null,
    imported_rows integer not null,
    warnings varchar(8000)
);

create table trade_history_record (
    id bigint generated by default as identity primary key,
    import_batch_id bigint not null,
    trade_timestamp timestamp not null,
    ticker varchar(16) not null,
    side varchar(32) not null,
    quantity double precision not null,
    price double precision not null,
    realized_pnl double precision,
    account varchar(128),
    strategy_type varchar(64),
    market_state varchar(64),
    constraint fk_trade_history_record_batch
        foreign key (import_batch_id) references trade_history_import_batch(id)
);

create index idx_trade_history_record_ticker_timestamp
    on trade_history_record(ticker, trade_timestamp desc);

create index idx_trade_history_record_batch
    on trade_history_record(import_batch_id);
