-- V3: Trader notes — freeform text annotations attached to a candidate.
-- A candidate may have zero or more notes; they are append-only.

create table trader_note (
    id           bigint generated by default as identity primary key,
    candidate_id varchar(64)   not null,
    symbol       varchar(16)   not null,
    note_text    varchar(4000) not null,
    created_at   timestamp     not null,
    author       varchar(128)
);

create index idx_trader_note_candidate_id on trader_note(candidate_id);
create index idx_trader_note_created_at   on trader_note(created_at desc);
