package dev.reddragon.ingestion.models;

import dev.reddragon.ingestion.utilities.IngestionTextUtils;
import lombok.Builder;
import lombok.Value;
import lombok.experimental.Accessors;

import java.time.Instant;
import java.util.Objects;

/**
 * One opportunity surfaced by Layer 1 of the MD architecture ("Opportunity
 * Discovery Engine"). It carries the raw catalyst, its provenance, and four
 * normalized 0.0-1.0 quality scores that downstream layers use to decide
 * whether to spend more time on it.
 *
 * <p><b>For a junior developer:</b> this is a value object — immutable,
 * compared by content, with fluent accessors. To build one:
 *
 * <pre>{@code
 *   TradeCandidate c = TradeCandidate.builder()
 *       .candidateId("ABC123")
 *       .symbol("NVDA")
 *       .catalystType(CandidateCatalystType.SEC_FILING)
 *       .sourceType(SourceType.SEC_EDGAR)
 *       .structuralRealityScore(0.7)
 *       .materialSignificanceScore(0.6)
 *       .earlynessScore(0.8)
 *       .reflexivityPotentialScore(0.5)
 *       .build();
 * }</pre>
 *
 * The builder is generated by Lombok {@code @Builder}, so there is no
 * separate Builder file in this package. {@code toBuilder()} returns a
 * pre-populated builder for cheap "copy with modifications".
 */
@Value
@Accessors(fluent = true)
public class TradeCandidate {

    String candidateId;
    String symbol;
    String companyName;
    CandidateCatalystType catalystType;
    SourceType sourceType;
    String sourceId;
    String sourceUrl;
    Instant observedAt;
    String headline;
    String summary;
    double structuralRealityScore;
    double materialSignificanceScore;
    double earlynessScore;
    double reflexivityPotentialScore;

    /**
     * All-args constructor — also the target of the Lombok-generated builder.
     * Runs cleanup ({@link IngestionTextUtils}) and range validation so the
     * value object can never be constructed in an inconsistent state.
     */
    @Builder(toBuilder = true)
    public TradeCandidate(
            String candidateId,
            String symbol,
            String companyName,
            CandidateCatalystType catalystType,
            SourceType sourceType,
            String sourceId,
            String sourceUrl,
            Instant observedAt,
            String headline,
            String summary,
            double structuralRealityScore,
            double materialSignificanceScore,
            double earlynessScore,
            double reflexivityPotentialScore
    ) {
        this.candidateId = IngestionTextUtils.requireText(candidateId, "candidateId");
        this.symbol = IngestionTextUtils.normalizeSymbol(symbol);
        this.companyName = IngestionTextUtils.clean(companyName);
        this.catalystType = Objects.requireNonNull(catalystType, "catalystType is required");
        this.sourceType = sourceType == null ? SourceType.MANUAL : sourceType;
        this.sourceId = IngestionTextUtils.clean(sourceId);
        this.sourceUrl = IngestionTextUtils.clean(sourceUrl);
        this.observedAt = observedAt == null ? Instant.now() : observedAt;
        this.headline = IngestionTextUtils.clean(headline);
        this.summary = IngestionTextUtils.clean(summary);
        this.structuralRealityScore = requireNormalized("structuralRealityScore", structuralRealityScore);
        this.materialSignificanceScore = requireNormalized("materialSignificanceScore", materialSignificanceScore);
        this.earlynessScore = requireNormalized("earlynessScore", earlynessScore);
        this.reflexivityPotentialScore = requireNormalized("reflexivityPotentialScore", reflexivityPotentialScore);
    }

    /** True if structural-reality is high enough that we trust the catalyst is real (>= 0.65). */
    public boolean hasCredibleStructuralCatalyst() {
        return structuralRealityScore >= 0.65;
    }

    private static double requireNormalized(String fieldName, double value) {
        if (value < 0.0 || value > 1.0) {
            throw new IllegalArgumentException(fieldName + " must be between 0.0 and 1.0");
        }
        return value;
    }
}
