-- V4: Verdict overrides — trader-supplied manual overrides of the validation engine verdict.
-- Overrides are audit-trailed; the original verdict_id is preserved.

create table verdict_override (
    id               bigint generated by default as identity primary key,
    verdict_id       bigint        not null,
    candidate_id     varchar(64)   not null,
    symbol           varchar(16)   not null,
    original_verdict varchar(32)   not null,
    override_verdict varchar(32)   not null,
    reason           varchar(1024),
    overridden_at    timestamp     not null,
    author           varchar(128)
);

create index idx_verdict_override_candidate_id on verdict_override(candidate_id);
create index idx_verdict_override_overridden_at on verdict_override(overridden_at desc);
