package dev.reddragon.validation.model;

/**
 * Machine-readable explanation codes for validation decisions.
 */
public enum ReasonCode {
    STRUCTURAL_CATALYST_CONFIRMED,
    STRUCTURAL_CATALYST_WEAK,
    CATALYST_NOT_CREDIBLE,
    CATALYST_MISSING,

    MATERIAL_IMPACT_HIGH,
    MATERIAL_IMPACT_MEDIUM,
    MATERIAL_IMPACT_LOW,
    MATERIAL_IMPACT_INSUFFICIENT,

    EARLY_UNKNOWN_BUT_REAL,
    EARLY_EMERGING_PROPAGATION,
    SOCIAL_ACCELERATION_CAUTION,
    MAINSTREAM_SATURATION,
    EUPHORIC_REFLEXIVITY,

    EQUILIBRIUM_RESTORATION_LIKELY,
    EQUILIBRIUM_ROTATIONAL_SUPPORTIVE,
    EQUILIBRIUM_DIRECTIONAL_HOSTILE,
    EQUILIBRIUM_UNSTABLE_VOLATILITY,
    EQUILIBRIUM_LIQUIDITY_DEGRADED,

    REFLEXIVITY_FORMING,
    REFLEXIVITY_NOT_YET_VISIBLE,
    REFLEXIVITY_OVEREXTENDED,

    ASYMMETRY_FAVORABLE,
    ASYMMETRY_COMPRESSED,
    ASYMMETRY_UNFAVORABLE,

    REGIME_SUPPORTIVE,
    REGIME_NEUTRAL,
    REGIME_HOSTILE,

    DEPLOYMENT_CONCENTRATION_CANDIDATE,
    DEPLOYMENT_STANDARD_REVIEW,
    DEPLOYMENT_PROBE_ONLY,
    DEPLOYMENT_OBSERVE_ONLY,
    DEPLOYMENT_REJECTED,

    REQUIRED_DATA_MISSING,
    SCORE_BELOW_THRESHOLD,
    HARD_GATE_FAILED
}
