spring:
  datasource:
    url: ${RED_DRAGON_DB_URL}
    username: ${RED_DRAGON_DB_USERNAME}
    password: ${RED_DRAGON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN
    dev.reddragon: INFO
