spring:
  application:
    name: red-dragon

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    dev.reddragon: DEBUG
