package dev.reddragon.analytics.model;

/**
 * Contradiction or warning patterns that challenge the setup thesis.
 */
public enum AdversarialFindingType {
    HYPE_WITHOUT_STRUCTURE,
    LATE_NARRATIVE_AFTER_REPRICING,
    OPTIONS_CHASE_WITHOUT_REALITY,
    VOLATILITY_WITH_LIQUIDITY_DETERIORATION,
    MATERIALITY_WITHOUT_MARKET_RESPONSE,
    SECTOR_SYMPATHY_WITH_WEAK_CATALYST,
    STRONG_CATALYST_ISOLATED_PROPAGATION,
    VWAP_RECLAIM_WITH_WEAK_EQUILIBRIUM,
    HIGH_MENTION_LOW_COHERENCE,
    ASYMMETRY_COMPRESSED_BY_EXTENSION
}
