-- =============================================================================
-- red-dragon — full database setup for PostgreSQL
-- =============================================================================
--
-- One-shot schema script. Equivalent to running every Flyway migration
-- (V1 through V9) against a fresh database, with PostgreSQL-native syntax.
--
-- Usage:
--   1. Create the database and a user that owns it:
--
--        createdb reddragon
--        createuser -P reddragon              # set a password
--        psql -d reddragon -c "alter database reddragon owner to reddragon;"
--
--   2. Run this script:
--
--        psql -h localhost -U reddragon -d reddragon -f red_dragon_setup.sql
--
--   3. Configure the app to point at this database via environment variables:
--
--        export RED_DRAGON_DB_URL=jdbc:postgresql://localhost:5432/reddragon
--        export RED_DRAGON_DB_USERNAME=reddragon
--        export RED_DRAGON_DB_PASSWORD=<the password from step 1>
--        export RED_DRAGON_DB_DRIVER=org.postgresql.Driver
--        export SPRING_PROFILES_ACTIVE=prod
--
--   4. Boot the app: mvn -pl app spring-boot:run
--
-- Notes:
--   - Idempotent. Safe to re-run; tables only created if missing.
--   - All FKs from V9 (and the inline FKs in V4/V5/V6/V8) are included.
--   - The single Flyway version table (flyway_schema_history) is NOT created
--     here. If you want Flyway to take over future migrations against this DB,
--     run `flyway baseline -baselineVersion=9` once after this script.
--   - JPA in the app runs with ddl-auto=validate, so column names and types
--     MUST match the entities. This script tracks the entities verbatim as of
--     the current head of main.
-- =============================================================================

\echo '*** red-dragon schema setup starting ***'

begin;

-- -----------------------------------------------------------------------------
-- 1. CANDIDATE (L1/L2 — ingestion output, the parent of most other rows)
-- -----------------------------------------------------------------------------
create table if not exists candidate (
    candidate_id   varchar(64)   primary key,
    symbol         varchar(16)   not null,
    company_name   varchar(256),
    catalyst_type  varchar(64)   not null,
    source_type    varchar(64)   not null,
    source_id      varchar(256),
    source_url     varchar(1024),
    observed_at    timestamp     not null,
    headline       varchar(512),
    summary        varchar(4000)
);

create index if not exists idx_candidate_symbol_observed_at
    on candidate (symbol, observed_at desc);

-- -----------------------------------------------------------------------------
-- 2. MARKET_BAR (L2 — cached EOD OHLCV bars per symbol/date)
-- -----------------------------------------------------------------------------
create table if not exists market_bar (
    id           bigint generated by default as identity primary key,
    symbol       varchar(16)      not null,
    bar_date     date             not null,
    open_price   double precision not null,
    high_price   double precision not null,
    low_price    double precision not null,
    close_price  double precision not null,
    volume       bigint           not null,
    unique (symbol, bar_date)
);

create index if not exists idx_market_bar_symbol_date
    on market_bar (symbol, bar_date desc);

-- -----------------------------------------------------------------------------
-- 3. MARKET_SNAPSHOT (L2 — per-candidate market features at decision time)
-- -----------------------------------------------------------------------------
create table if not exists market_snapshot (
    id                          bigint generated by default as identity primary key,
    candidate_id                varchar(64)      not null,
    symbol                      varchar(16)      not null,
    observed_at                 timestamp        not null,
    latest_close                double precision not null,
    previous_close              double precision not null,
    gap_percent                 double precision not null,
    average_true_range          double precision not null,
    range_position              double precision not null,
    average_volume              double precision not null,
    liquidity_score             double precision not null,
    volatility_stability_score  double precision not null,
    quality                     varchar(64)      not null,
    notes                       varchar(4000),
    -- V7 additions
    relative_volume             double precision,
    vwap_deviation              double precision,
    directional_persistence     double precision,
    -- V9 relationship
    constraint fk_market_snapshot_candidate
        foreign key (candidate_id) references candidate (candidate_id)
);

create index if not exists idx_market_snapshot_candidate_id
    on market_snapshot (candidate_id);

create index if not exists idx_market_snapshot_symbol_observed_at
    on market_snapshot (symbol, observed_at desc);

-- -----------------------------------------------------------------------------
-- 4. ANALYTICS_SNAPSHOT (L3-L6 — per-candidate scoring breakdown)
-- -----------------------------------------------------------------------------
create table if not exists analytics_snapshot (
    id                          bigint generated by default as identity primary key,
    candidate_id                varchar(64)      not null,
    symbol                      varchar(16)      not null,
    observed_at                 timestamp        not null,
    regime_label                varchar(64)      not null,
    regime_compatibility_score  double precision not null,
    asymmetry_score             double precision not null,
    equilibrium_quality_score   double precision not null,
    reflexivity_potential_score double precision not null,
    deployment_confidence_score double precision not null,
    reason_notes                varchar(4000),
    constraint fk_analytics_snapshot_candidate
        foreign key (candidate_id) references candidate (candidate_id)
);

create index if not exists idx_analytics_snapshot_candidate_id
    on analytics_snapshot (candidate_id);

create index if not exists idx_analytics_snapshot_symbol_observed
    on analytics_snapshot (symbol, observed_at desc);

-- -----------------------------------------------------------------------------
-- 5. VALIDATION_VERDICT (L3/L5 — pass/watch/reject + deployment tier)
-- -----------------------------------------------------------------------------
create table if not exists validation_verdict (
    id              bigint generated by default as identity primary key,
    candidate_id    varchar(64)      not null,
    symbol          varchar(16)      not null,
    verdict         varchar(32)      not null,
    deployment_tier varchar(32)      not null,
    score           double precision not null,
    idempotency_key varchar(128),
    reason_codes    varchar(4000),
    explanations    varchar(8000),
    created_at      timestamp        not null,
    -- V9 relationship
    constraint fk_validation_verdict_candidate
        foreign key (candidate_id) references candidate (candidate_id)
);

create index if not exists idx_validation_symbol_created_at
    on validation_verdict (symbol, created_at desc);

create index if not exists idx_validation_verdict_candidate_id
    on validation_verdict (candidate_id);

create unique index if not exists uk_validation_verdict_idempotency_key
    on validation_verdict (idempotency_key);

-- -----------------------------------------------------------------------------
-- 6. VERDICT_OVERRIDE (trader manual override of a verdict — L5 audit trail)
-- -----------------------------------------------------------------------------
create table if not exists verdict_override (
    id               bigint generated by default as identity primary key,
    verdict_id       bigint        not null,
    candidate_id     varchar(64)   not null,
    symbol           varchar(16)   not null,
    original_verdict varchar(32)   not null,
    override_verdict varchar(32)   not null,
    reason           varchar(1024),
    overridden_at    timestamp     not null,
    author           varchar(128),
    constraint fk_verdict_override_verdict
        foreign key (verdict_id)   references validation_verdict (id),
    constraint fk_verdict_override_candidate
        foreign key (candidate_id) references candidate (candidate_id)
);

create index if not exists idx_verdict_override_candidate_id
    on verdict_override (candidate_id);

create index if not exists idx_verdict_override_verdict_id
    on verdict_override (verdict_id);

create index if not exists idx_verdict_override_overridden_at
    on verdict_override (overridden_at desc);

-- -----------------------------------------------------------------------------
-- 7. TRADER_NOTE (free-form notes pinned to a candidate)
-- -----------------------------------------------------------------------------
create table if not exists trader_note (
    id           bigint generated by default as identity primary key,
    candidate_id varchar(64)   not null,
    symbol       varchar(16)   not null,
    note_text    varchar(4000) not null,
    created_at   timestamp     not null,
    author       varchar(128),
    constraint fk_trader_note_candidate
        foreign key (candidate_id) references candidate (candidate_id)
);

create index if not exists idx_trader_note_candidate_id
    on trader_note (candidate_id);

create index if not exists idx_trader_note_created_at
    on trader_note (created_at desc);

-- -----------------------------------------------------------------------------
-- 8. CALIBRATION_OUTCOME (L8 — realized outcomes for drift detection)
--    Note: candidate_id is NOT a FK because historical outcomes from before
--    the system was running may reference candidates that never existed
--    in `candidate`.
-- -----------------------------------------------------------------------------
create table if not exists calibration_outcome (
    id                          bigint generated by default as identity primary key,
    candidate_id                varchar(128)     not null,
    symbol                      varchar(16)      not null,
    observed_at                 timestamp        not null,

    -- Snapshot of the candidate's scoring breakdown at decision time
    structural_reality_score    double precision not null,
    material_significance_score double precision not null,
    earlyness_score             double precision not null,
    equilibrium_quality_score   double precision not null,
    reflexivity_potential_score double precision not null,
    asymmetry_score             double precision not null,
    regime_compatibility_score  double precision not null,
    deployment_confidence_score double precision not null,

    -- Realized outcome
    realized_return             double precision not null,
    max_drawdown                double precision not null,
    days_held                   integer          not null,
    thesis_worked               boolean          not null
);

create index if not exists idx_calibration_outcome_symbol_observed_at
    on calibration_outcome (symbol, observed_at desc);

create index if not exists idx_calibration_outcome_observed_at
    on calibration_outcome (observed_at desc);

-- -----------------------------------------------------------------------------
-- 9. BACKTEST_RESULT (replay-engine outputs grouped by run_id)
--    Note: candidate_id is NOT a FK because backtest runs commonly reference
--    historical candidates that don't (yet) exist in `candidate`.
-- -----------------------------------------------------------------------------
create table if not exists backtest_result (
    id            bigint generated by default as identity primary key,
    run_id        varchar(64)      not null,
    strategy_name varchar(128)     not null,
    symbol        varchar(16)      not null,
    candidate_id  varchar(64)      not null,
    verdict       varchar(32)      not null,
    score         double precision not null,
    tested_at     timestamp        not null
);

create index if not exists idx_backtest_run_id
    on backtest_result (run_id);

-- -----------------------------------------------------------------------------
-- 10. SCHWAB_TOKEN (OAuth access + refresh tokens — one row per refresh)
-- -----------------------------------------------------------------------------
create table if not exists schwab_token (
    id            bigint generated by default as identity primary key,
    access_token  varchar(4000) not null,
    refresh_token varchar(4000) not null,
    issued_at     timestamp     not null,
    expires_at    timestamp     not null,
    token_type    varchar(32)   not null default 'Bearer'
);

create index if not exists idx_schwab_token_issued_at
    on schwab_token (issued_at desc);

-- -----------------------------------------------------------------------------
-- 11. INTRADAY_BAR (L2 — minute-level bars from a provider)
-- -----------------------------------------------------------------------------
create table if not exists intraday_bar (
    id          bigint generated by default as identity primary key,
    symbol      varchar(16)      not null,
    start_time  timestamp        not null,
    open_price  double precision not null,
    high_price  double precision not null,
    low_price   double precision not null,
    close_price double precision not null,
    volume      bigint           not null,
    vwap        double precision not null,
    created_at  timestamp        not null,
    unique (symbol, start_time)
);

create index if not exists idx_intraday_bar_symbol_start_time
    on intraday_bar (symbol, start_time desc);

-- -----------------------------------------------------------------------------
-- 12. MARKET_QUOTE_OBSERVATION (L2 — single-shot bid/ask/last observations)
-- -----------------------------------------------------------------------------
create table if not exists market_quote_observation (
    id          bigint generated by default as identity primary key,
    symbol      varchar(16)      not null,
    observed_at timestamp        not null,
    last_price  double precision not null,
    bid_price   double precision not null,
    ask_price   double precision not null,
    volume      bigint           not null,
    quality     varchar(64)      not null,
    notes       varchar(4000)
);

create index if not exists idx_market_quote_symbol_observed_at
    on market_quote_observation (symbol, observed_at desc);

-- -----------------------------------------------------------------------------
-- 13. TRADE_HISTORY_IMPORT_BATCH (one row per CSV import run)
-- -----------------------------------------------------------------------------
create table if not exists trade_history_import_batch (
    id            bigint generated by default as identity primary key,
    imported_at   timestamp     not null,
    total_rows    integer       not null,
    imported_rows integer       not null,
    warnings      varchar(8000)
);

-- -----------------------------------------------------------------------------
-- 14. TRADE_HISTORY_RECORD (one row per normalised fill from the broker CSV)
-- -----------------------------------------------------------------------------
create table if not exists trade_history_record (
    id              bigint generated by default as identity primary key,
    import_batch_id bigint           not null,
    trade_timestamp timestamp        not null,
    ticker          varchar(16)      not null,
    side            varchar(32)      not null,
    quantity        double precision not null,
    price           double precision not null,
    realized_pnl    double precision,
    account         varchar(128),
    strategy_type   varchar(64),
    market_state    varchar(64),
    constraint fk_trade_history_record_batch
        foreign key (import_batch_id) references trade_history_import_batch (id)
);

create index if not exists idx_trade_history_record_ticker_timestamp
    on trade_history_record (ticker, trade_timestamp desc);

create index if not exists idx_trade_history_record_batch
    on trade_history_record (import_batch_id);

commit;

\echo '*** red-dragon schema setup complete ***'

-- =============================================================================
-- Relationship summary (for reference)
-- =============================================================================
--
-- candidate (PK candidate_id)
--   ├── analytics_snapshot.candidate_id     FK -> candidate.candidate_id
--   ├── market_snapshot.candidate_id        FK -> candidate.candidate_id
--   ├── validation_verdict.candidate_id     FK -> candidate.candidate_id
--   │       └── verdict_override.verdict_id FK -> validation_verdict.id
--   ├── verdict_override.candidate_id       FK -> candidate.candidate_id
--   └── trader_note.candidate_id            FK -> candidate.candidate_id
--
-- trade_history_import_batch (PK id)
--   └── trade_history_record.import_batch_id FK -> trade_history_import_batch.id
--
-- Tables with NO foreign keys (intentional — soft references only):
--   - calibration_outcome.candidate_id      (historical outcomes pre-date the system)
--   - backtest_result.candidate_id          (replay can target arbitrary historical ids)
--   - market_bar                            (independent — keyed by symbol+date)
--   - intraday_bar                          (independent)
--   - market_quote_observation              (independent)
--   - schwab_token                          (operational, not pipeline-scoped)
